image: Visual Studio 2017
configuration: Release

install:
  ## Prepare .sln with cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build
  - cd cmake_build
  - cmake --version
  - cmake c:\projects\ctf

build_script: msbuild "C:\projects\ctf\cmake_build\ctf.sln"

artifacts:
 - path: cmake_build\Release\**\*.*
